baseURL: "https://pilliac.netlify.app/" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: PILLIAC
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: true
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
googleAnalytics: G-XQ9FP8WSGT

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 7
                - name: About
                  url: about/
                  weight: 2
#                - name: WiKi
#                  url: https://github.com/adityatelange/hugo-PaperMod/wiki/
#                - name: Discord
#                  url: https://discord.gg/ahpmTvhVmp

#    fr:
#        languageName: ":fr:"
#        languageAltTitle: "Who Are You?"
#        weight: 2
#        title: PaperModL2
#        taxonomies:
#          category: FRcategories
#          tag: FRtags
#          series: FRseries
#        profileMode:
#            enabled: true
#            title: PaperMod
#            imageUrl: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f317.svg"
#            imageTitle: ProfileMode image
#            # imageWidth: 120
#            # imageHeight: 120
#            subtitle:
#                "â˜„ï¸ Fast | â˜ï¸ Fluent | ðŸŒ™ Smooth | ðŸ“± Responsive"
#            buttons:
#                - name: Blog
#                  url: posts
#                - name: Profile Mode
#                  url: https://github.com/adityatelange/hugo-PaperMod/wiki/Features#profile-mode
#        menu:
#            main:
#                - name: Archive
#                  url: archives/
#                  weight: 5
#                - name: FRTags
#                  url: frtags
#                  weight: 10
#                - name: FRCategories
#                  url: frcategories
#                  weight: 10
#                - name: FRSeries
#                  url: frseries
#                  weight: 10
#                - name: NullLink
#                  url: "#"

#    fa:
#        languagedirection: rtl
#        weight: 3
#        title: PaperMod RTL
#        homeInfoParams:
#            Title: "Hi there \U0001F44B"
#            Content: Welcome to RTL layout
#        taxonomies:
#          category: FAcategories
#          tag: FAtags
#          series: FAseries
#        menu:
#            main:
#                - name: FATags
#                  url: fatags
#                  weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "My musings."
    author: Pilliac
    # author: ["Me", "You"] # multiple authors

    defaultTheme: dark # auto, light, dark
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: false
    ShowRssButtonInSectionTermList: false
    ShowToc: true
    comments: true
    images: ["icon.png"]

    profileMode:
        enabled: false
        title: PaperMod
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    aboutPage:
        enabled: true
        title: PILLIAC
        imageUrl: "about.png"
        imageTitle: Art by @discountsupervillain
        # imageWidth: 120
        # imageHeight: 120
        subtitle: >
            
            (Silver in my language + ILLIAC)
            
            - Haven't developed anything good yet.
            
            - If I do, I'll add em over there (*points downwards*).

        buttons:
            - name: Contact
              url: "mailto: pilliac.dev@gmail.com"
#            - name: Profile Mode
#              url: https://github.com/silveriogg

    homeInfoParams:
        Title: "I DID A THING!"
        Content: >
            Welcome to this little site.

            - I just write stuff I feel like writing.

            - Please don't judge me. Or do.

            - Just don't expect to learn anything, alright?

    socialIcons:
        - name: github
          url: "https://github.com/silveriogg"
        - name: twitter
          url: "https://twitter.com/BusyCharacter"
        - name: KoFi
          url: "https://ko-fi.com/pilliac"
#        - name: Rss
#          url: "index.xml"

#    editPost:
#        URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
#        Text: "Suggest Changes" # edit text
#        appendFilePath: true # to append file path to Edit link

    label:
         text: "PILLIAC"
         icon: 'icon.png'
         iconHeight: 20

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
        disableHLJS: true
#        favicon: "<link / abs url>"
#        favicon16x16: "<link / abs url>"
#        favicon32x32: "<link / abs url>"
#        apple_touch_icon: "<link / abs url>"
#        safari_pinned_tab: "<link / abs url>"

#    cover:
#         hidden: true # hide everywhere but not in structured data
#         hiddenInList: true # hide on list pages and home
#         hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
#        guessSyntax: true
        # lineNos: true
        style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
