---
baseURL: https://pilliac.netlify.app/
title: PILLIAC
paginate: "5"
theme: PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: true
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: G-XQ9FP8WSGT

minify:
  disableXML: true
languages:
  en:
    languageName: English
    weight: "1"
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
#      - name: Archive
#        url: archives
#        weight: "5"
      - name: Search
        url: search/
        weight: "10"
      - name: Tags
        url: tags/
        weight: "3"
      - name: About
        url: about/
        weight: "1"
      - name: Posts
        url: posts/
        weight: "2"

outputs:
  home:
  - HTML
  - RSS
  - JSON
params:
  env: production
  description: My musings.
  author: Pilliac
  defaultTheme: dark
  ShowShareButtons: false
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowRssButtonInSectionTermList: false
  ShowToc: true
  comments: true
  images:
  - icon.png
#  profileMode:
#    enabled: false
#    title: PaperMod
#    imageUrl: "#"
#    imageTitle: my image
#    buttons:
#    - name: Archives
#      url: archives
#    - name: Tags
#      url: tags
  aboutPage:
    enabled: true
    title: PILLIAC
    imageUrl: about.png
    imageTitle: Art by @discountsupervillain
    subtitle: |2

      (Silver in my language + ILLIAC)
      - Haven't developed anything good yet.
      - If I do, I'll add em over there (*points downwards*).
    buttons:
    - name: Contact
      url: 'mailto: pilliac.dev@gmail.com'
  homeInfoParams:
    Title: WELCOME BACK!
    Content: |
      This tagline is only wrong the first time.
      - I just write stuff I feel like writing.
  socialIcons:
  - name: github
    url: https://github.com/siruthesiru
  - name: twitter
    url: https://twitter.com/BusyCharacter
  - name: KoFi
    url: https://ko-fi.com/pilliac
  label:
    text: PILLIAC
    icon: icon.png
    iconHeight: "20"
  assets:
    disableHLJS: false
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    style: gruvbox-dark

privacy:
  vimeo:
    disabled: false
    simple: true
  twitter:
    disabled: false
    enableDNT: true
    simple: true
  instagram:
    disabled: false
    simple: true
  youtube:
    disabled: false
    privacyEnhanced: true
services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
